### PR TITLE
OOP school library: refactor your code

### PR DESCRIPTION
**Pull request by habasm**
Refactoring of the code by @habasm, even though the work is pairing my partner is not available. 

### Project requirements

At this point your codebase is pretty big. The `main.rb` file may be especially large at this point. Let's try to clean things up!

- Make sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Follow SOLID principles.
- Pay special attention to the "Single-responsibility Principle".
    - Make sure that the role of `main.rb` is only to start your code and ask the user for the initial choice of options (or to quit).
    - Extract some pieces of logic into separate class(es).

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @habasm 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't show contributions from your coding partner as this is a paired programming activity you are to work with your partner on this project 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by habasm** [comment]
@Davidosky007 Please see what I am writing on the description. I am solo this week, because my partner is not present.

**Comment by Davidosky007** [comment]
> @Davidosky007 Please see what I am writing on the description. I am solo this week, because my partner is not present.

Kindly note that only student success can give you the go ahead to work solo , if you have any mail from them to back this up you can attach it to your PR

**Comment by habasm** [comment]
image

@Davidosky007  this is what happening. I am contacting to the student success, and my partner is left to the group

**Comment by habasm** [comment]
image

**Review by sumairq — APPROVED** [review]
### Hi @habasm , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
